- name: Install dependencies
  run: |
    cd serinova-checklist-sistemi/backend
    npm install --legacy-peer-deps

- name: Build
  run: |
    cd serinova-checklist-sistemi/backend
    npm run build --if-present

- name: Run tests with coverage
  run: |
    cd serinova-checklist-sistemi/backend
    npm run test:cov

- name: SonarCloud Scan
  uses: SonarSource/sonarcloud-github-action@master
  with:
    projectBaseDir: ./serinova-checklist-sistemi/backend
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
